name: Dry Run Publish

on:
  pull_request:
    branches: [main, workflow-testing]

jobs:
  dry-run-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests and Check Coverage
        run: npm run coverage

      - name: Build Extension
        run: npm run build

      - name: Package Extension
        run: vsce package

      - name: Validate VSIX Package
        run: |
          if [ ! -f *.vsix ]; then
            echo "VSIX package not found!"
            exit 1
          fi
          echo "VSIX package successfully created."
