name: Test Coverage

on:
  push:
    branches: [main, workflow-testing]
  pull_request:
    branches: [main, workflow-testing]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Coverage Check
        run: npx c8 --check-coverage --lines 80 --functions 80 --branches 70 npm test

      - name: Upload Coverage Report
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage
